micronaut:
  application:
    name: destiny2

endpoints:
  health:
    enabled: true

jackson:
  serialization:
    writeDatesAsTimestamps: false

# Scylla/Cassandra Configuration
cassandra:
  default:
    basic:
      contact-points:
        - ${cassandra_contact_points:localhost}
      session-keyspace: ${cassandra_session_keyspace:destiny2}
      load-balancing-policy:
        local-datacenter: ${cassandra_local_datacenter:datacenter1}
